version: '3.1'

services:
  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "37017:27017"
    volumes:
      - mongo-data:/data/db  

volumes:
  mongo-data:  
